const phrases = [
  "Réfléchis à 3 choses pour lesquelles tu peux te réjouir pour cette année", 
  "Prends le temps d’être attentionné envers toi-même",
  "Sème la joie autour de toi en faisant des choses attentionnées pour les autres",
  "Fais la liste des choses pour lesquelles tu es reconnaissant et explique pourquoi",
  "Bouge ! Pratique une activité physique (idéalement extérieur)",
  "Trouve quelque chose de positif à dire à chaque personne que tu rencontres aujourd’hui",
  "Prends 10 minutes pour rester assis et pour simplement respirer",
  "Cherche en chacun de ce qu’il y a de meilleur et remarquent leurs points forts",
  "Apprends quelque chose de nouveau puis partage ton expérience",
  "Remercie 3 personnes en leurs expliquant pourquoi",
  "Discute de façon amicale avec un inconnu",
  "Eteins tout appareil électronique deux heures avant de te coucher",
  "Soi aimable envers toi-même quand tu fais une erreur",
  "Prends un chemin différent aujourd’hui et note ce que tu vois",
  "Change de perspective par rapport à un souci et essaie de t’en détacher",
  "Sors et fait attention à 5 belles choses",
  "Nourris-toi vraiment sainement aujourd’hui",
  "Fais bouger les choses une bonne cause",
  "Reprends contact avec un ancien ami qui te manque",
  "Va au lit de bonne heure pour vraiment recharger tes batteries",
  "Fais un petit pas en avant dans la direction d’un but qui t’est important",
  "Essaye quelque chose de nouveau afin d’élargir ta zone de confort",
  "Décide de motiver les autres plutôt que de les décourager",
  "Fais quelque chose de joyeux et encourage les autres à y participer aussi",
  "Mets tes appareils électroniques de côté et concentre-toi vraiment sur ceux qui t’entourent",
  "Dis bonjour à un voisin et fais un peu mieux connaissance",
  "Challenge tes idées négatives en cherchant le positif",
  "Compte combien de personnes tu peux faire sourire aujourd’hui",
  "Mets à profit un de tes points forts d’une nouvelle façon",
  "Demande autour de toi ce qui leur a apporté du plaisir récemment",
  "Ecris les espoirs et les plans que tu as pour le futur",  
];

export default phrases;

